import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";
import { Source_Serif_4 } from "next/font/google";
import GithubSvg from "@/Components/GithubSvg";
import NavigationBar from "@/Components/NavigationBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const sourceSerif4 = Source_Serif_4({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const gtagScript = `window.dataLayer = window.dataLayer || [];
                          function gtag(){dataLayer.push(arguments);}
                          gtag('js', new Date());
                          gtag('config', 'G-QHKRHVWX6T');`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Script async src="https://www.googletagmanager.com/gtag/js?id=G-QHKRHVWX6T" />
      <Script id="gtagScript" type="application/javascript">
        {gtagScript}
      </Script>
      <body
        className={`w-screen h-screen overflow-hidden flex flex-col justify-start items-center gap-0 box-border  bg-gray-50 ${sourceSerif4.className}`}
      >
        <GithubSvg />
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
